# NAME: Anirudh Veeraragavan,Rahul Sheth
# EMAIL: aveeraragavan@g.ucla.edu,rahulssheth@g.ucla.edu
# ID: 004767663,304779669

build: lab3a.c
		gcc -o lab3a -Wall -Wextra lab3a.c
		@echo "Executable created."

dist:
	@tar -cvzf lab3a-004767663.tar.gz lab3a.c Makefile README
	@echo "Distribution tarball created."

clean:
	@rm -f Makefile~ README~ lab3a lab3a-004767663.tar.gz
	@echo "All created files deleted."